# Generated by Django 4.1.1 on 2022-10-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('technology', 'Technology'), ('agriculture', 'Agriculture'), ('environment', 'Environment'), ('opinion', 'Opinion'), ('culture', 'Culture'), ('science', 'Science'), ('health', 'Health'), ('travel', 'Travel'), ('business', 'Business')], default='science', max_length=50),
        ),
    ]
